const state = { sectors: [], limitUps: new Map(), selected: null, stocks: [], type: 'all' };
const $ = id => document.getElementById(id);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[c]);

addEventListener('DOMContentLoaded', () => { $('refreshBtn').addEventListener('click', loadDashboard); $('sectorType').addEventListener('change', event => { state.type = event.target.value; loadSectors(); }); $('aiRefresh').addEventListener('click', () => updateAiBrief(true)); loadDashboard(); });

async function json(url, attempts = 3) { let lastError; for (let attempt = 0; attempt < attempts; attempt++) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 10000); try { const response = await fetch(url, { signal: controller.signal }); if (!response.ok) throw new Error(`行情接口返回 ${response.status}`); return await response.json(); } catch (error) { lastError = error; if (attempt < attempts - 1) await new Promise(resolve => setTimeout(resolve, 400 * (attempt + 1))); } finally { clearTimeout(timeout); } } throw lastError; }
function stockCode(market, code) { return `${market === 1 ? 'sh' : 'sz'}${code}`; }
function emCode(code) { return `${code.startsWith('sh') ? '1' : '0'}.${code.slice(2)}`; }
function formatAmount(value) { const amount = Number(value) || 0; return amount >= 100000000 ? `${(amount / 100000000).toFixed(1)}亿` : `${(amount / 10000).toFixed(0)}万`; }
function signed(value) { return `${Number(value) >= 0 ? '+' : ''}${Number(value).toFixed(2)}%`; }

async function loadDashboard() {
    $('marketState').textContent = '同步中'; $('dataStatus').textContent = '正在拉取真实行情'; $('refreshBtn').disabled = true;
    $('tradeDate').textContent = new Date().toLocaleDateString('zh-CN');
    try { await loadSectors(); $('marketState').textContent = '板块行情已连接'; $('dataStatus').textContent = '板块已加载，正在校验涨停标记'; await loadLimitUps(); if (state.selected && state.stocks.length) renderStocks(); $('marketState').textContent = '行情已连接'; $('dataStatus').textContent = '数据来自公开行情接口'; } catch (error) { const message = networkErrorMessage(error); $('marketState').textContent = '接口不可用'; $('dataStatus').textContent = message; if (!state.sectors.length) $('sectorList').innerHTML = `<div class="empty">${escapeHtml(message)}，未显示模拟数据。</div>`; } finally { $('refreshBtn').disabled = false; $('updateTime').textContent = new Date().toLocaleTimeString('zh-CN'); $('dataClock').textContent = new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }); }
}
function networkErrorMessage(error) { if (location.protocol === 'file:') return '请通过 HTTP 服务器打开页面（不要直接双击 HTML）'; if (error.name === 'TypeError' || /Failed to fetch/i.test(error.message)) return '行情接口连接失败，请稍后重试'; return error.message || '行情接口连接失败'; }
async function loadLimitUps() {
    const date = new Date().toISOString().slice(0, 10).replaceAll('-', '');
    const result = await json(`https://push2ex.eastmoney.com/getTopicZTPool?ut=7eea3edcaed734bea9cbfc24409ed989&dpt=wz.ztzt&Pageindex=0&pagesize=100&sort=fbt:asc&date=${date}`);
    const rows = result.data?.pool || []; const checked = []; for (let index = 0; index < rows.length; index += 5) { const batch = await Promise.all(rows.slice(index, index + 5).map(async row => { const code = stockCode(row.m, row.c); const currentPrice = Number(row.p) / 1000; const change = Number(row.zdp); const quote = await json(`https://push2delay.eastmoney.com/api/qt/stock/get?secid=${emCode(code)}&fields=f60`, 1).catch(() => ({ data: {} })); const quotedPrevious = Number(quote.data?.f60) / 100; const previousClose = quotedPrevious > 0 ? quotedPrevious : currentPrice / (1 + change / 100); const limitRate = row.n.includes('ST') ? 5 : (/^(30|68)/.test(row.c) ? 20 : /^(4|8)/.test(row.c) ? 30 : 10); const limitPrice = previousClose > 0 ? Math.round(previousClose * (1 + limitRate / 100) * 100) / 100 : null; return [code, { name: row.n, currentPrice, limitPrice, change, amount: Number(row.amount) }]; })); checked.push(...batch); } state.limitUps = new Map(checked); $('limitCount').textContent = state.limitUps.size || '--';
}
async function loadSectors() {
    const types = state.type === 'industry' ? ['m:90+t:2'] : state.type === 'concept' ? ['m:90+t:3'] : ['m:90+t:2', 'm:90+t:3'];
    const results = [];
    for (const type of types) {
        try { results.push(await loadAllSectorPages(type)); } catch (error) { console.warn(error.message); }
    }
    if (!results.some(rows => rows.length)) throw new Error('行业和概念板块接口暂时不可用');
    state.sectors = results.flat().map(row => ({ code: row.f12, name: row.f14, price: Number(row.f2), change: Number(row.f3), amount: Number(row.f6), up: Number(row.f104), down: Number(row.f105), flat: Number(row.f106) })).filter(item => item.name && Number.isFinite(item.change));
    $('sectorCount').textContent = state.sectors.length; const best = state.sectors[0]; $('hotSector').textContent = best?.name || '--'; renderSectors();
    if (!state.selected || !state.sectors.some(item => item.code === state.selected.code)) selectSector(state.sectors[0]); else selectSector(state.sectors.find(item => item.code === state.selected.code));
}
async function loadAllSectorPages(type) { const fields = 'f12,f14,f2,f3,f4,f5,f6,f104,f105,f106'; let host = 'push2delay.eastmoney.com'; const makeUrl = (page, source) => `https://${source}/api/qt/clist/get?pn=${page}&pz=100&po=1&np=1&fltt=2&invt=2&fid=f3&fs=${encodeURIComponent(type)}&fields=${fields}`; const fetchPage = async page => { const sources = [host, host === 'push2delay.eastmoney.com' ? 'push2.eastmoney.com' : 'push2delay.eastmoney.com']; for (const source of sources) { try { const result = await json(makeUrl(page, source), 1); host = source; return result; } catch (_) {} } throw new Error(`板块第${page}页接口不可用`); }; const first = await fetchPage(1); const total = Number(first.data?.total) || first.data?.diff?.length || 0; const pages = Math.ceil(total / 100); const rows = first.data?.diff || []; for (let page = 2; page <= pages; page++) { const result = await fetchPage(page); rows.push(...(result.data?.diff || [])); } return rows; }
function renderSectors() { $('sectorList').innerHTML = state.sectors.map((sector, index) => `<button class="sector-row ${state.selected?.code === sector.code ? 'active' : ''}" data-code="${escapeHtml(sector.code)}"><span class="rank">${String(index + 1).padStart(3, '0')}</span><span class="sector-name">${escapeHtml(sector.name)}<small>${sector.up || 0}涨 / ${sector.down || 0}跌</small></span><strong class="${sector.change >= 0 ? 'up' : 'down'}">${signed(sector.change)}</strong><span class="bar"><i style="width:${Math.min(100, Math.max(5, Math.abs(sector.change) * 11))}%"></i></span></button>`).join('') || '<div class="empty">暂无板块数据</div>'; document.querySelectorAll('.sector-row').forEach(row => row.addEventListener('click', () => selectSector(state.sectors.find(item => item.code === row.dataset.code)))); }
async function selectSector(sector) { if (!sector) return; state.selected = sector; renderSectors(); $('detailTitle').textContent = sector.name; $('detailSubtitle').textContent = `板块指数 ${sector.price || '--'} · 成交额 ${formatAmount(sector.amount)}`; $('detailBadge').textContent = `${sector.change >= 0 ? '强势' : '偏弱'}板块`; $('sectorMetrics').innerHTML = `<div><span>板块涨幅</span><strong class="${sector.change >= 0 ? 'up' : 'down'}">${signed(sector.change)}</strong></div><div><span>上涨家数</span><strong>${sector.up || '--'}</strong></div><div><span>涨停家数</span><strong>${state.limitUps.size ? '--' : '暂无'}</strong></div><div><span>领涨股</span><strong>读取中</strong></div>`; $('leaderList').innerHTML = '<div class="empty">正在读取成分股...</div>'; $('followerList').innerHTML = '<div class="empty">正在读取成分股...</div>';
    try { state.stocks = await loadConstituents(sector.code); const limitCount = state.stocks.filter(stock => state.limitUps.has(stock.code)).length; $('sectorMetrics').innerHTML = `<div><span>板块涨幅</span><strong class="${sector.change >= 0 ? 'up' : 'down'}">${signed(sector.change)}</strong></div><div><span>上涨家数</span><strong>${state.stocks.filter(stock => stock.change > 0).length}</strong></div><div><span>涨停家数</span><strong>${limitCount}</strong></div><div><span>领涨股</span><strong>${escapeHtml(state.stocks[0]?.name || '--')}</strong></div>`; renderStocks(); updateAiBrief(false); } catch (error) { $('leaderList').innerHTML = `<div class="empty">${escapeHtml(error.message)}，未显示模拟数据。</div>`; $('followerList').innerHTML = ''; }
}
async function loadConstituents(sectorCode) { const result = await json(`https://push2.eastmoney.com/api/qt/clist/get?pn=1&pz=100&po=1&np=1&fid=f3&fs=b:${encodeURIComponent(sectorCode)}&fields=f2,f3,f5,f6,f12,f14`); return (result.data?.diff || []).map(row => { const code = String(row.f12); return { code: stockCode(code.startsWith('6') ? 1 : 0, code), name: row.f14, price: Number(row.f2), change: Number(row.f3) / 100, volume: Number(row.f5), amount: Number(row.f6) }; }).filter(stock => stock.name && Number.isFinite(stock.change)).sort((a, b) => b.change - a.change); }
function stockRow(stock) { const limit = state.limitUps.get(stock.code); return `<a class="stock-row" href="stock_detail.html?code=${encodeURIComponent(stock.code)}&name=${encodeURIComponent(stock.name)}&price=${limit?.limitPrice || ''}&currentPrice=${stock.price}&change=${stock.change}" target="_blank" rel="noopener noreferrer"><span class="stock-name"><b>${escapeHtml(stock.name)}</b><small>${escapeHtml(stock.code)}${limit?.limitPrice ? ` · 涨停 ¥${limit.limitPrice.toFixed(2)}` : ''}</small></span><strong class="${stock.change >= 0 ? 'up' : 'down'}">${signed(stock.change)}</strong><span>${limit ? (limit.limitPrice ? '<mark>涨停</mark>' : '待核验') : formatAmount(stock.amount)}</span><span class="stock-arrow">↗</span></a>`; }
function renderStocks() { const leaders = [...state.stocks].sort((a, b) => (state.limitUps.has(b.code) - state.limitUps.has(a.code)) || b.change - a.change || b.amount - a.amount).slice(0, 5); const followers = state.stocks.filter(stock => !leaders.some(item => item.code === stock.code)).slice(0, 8); $('leaderList').innerHTML = leaders.map(stockRow).join('') || '<div class="empty">暂无成分股数据</div>'; $('followerList').innerHTML = followers.map(stockRow).join('') || '<div class="empty">暂无跟随股数据</div>'; }
async function updateAiBrief(force) { const sector = state.selected; if (!sector || !state.stocks.length) return; $('aiRefresh').disabled = true; $('aiText').textContent = '正在生成分析...'; const limit = state.stocks.filter(stock => state.limitUps.has(stock.code)).length; const rising = state.stocks.filter(stock => stock.change > 0).length; const lead = state.stocks[0]; const local = `${sector.name}当前板块涨幅${signed(sector.change)}，成分股上涨${rising}家，涨停${limit}家，领涨为${lead?.name || '--'}（${signed(lead?.change || 0)}）。${limit >= 2 ? '涨停密度较高，短线情绪偏强，需观察龙头封单与跟随股是否扩散。' : rising > state.stocks.length / 2 ? '上涨家数占优但涨停集中度一般，更像趋势性扩散，关注成交额是否持续放大。' : '板块内部出现分化，暂不宜仅凭板块涨幅判断主线强度。'}`; $('aiText').textContent = local; const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 1500); try { const response = await fetch('/api/ai/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sector, stocks: state.stocks.slice(0, 20), limitUps: [...state.limitUps.keys()] }), signal: controller.signal }); if (response.ok) { const data = await response.json(); if (data.analysis) $('aiText').textContent = data.analysis; } } catch (_) { /* 未配置服务端时保留透明的本地统计分析 */ } finally { clearTimeout(timeout); } $('aiSource').textContent = force ? '基于刚刚拉取的实时字段重新生成' : '基于实时字段的规则摘要 · 可接入 /api/ai/analyze'; $('aiRefresh').disabled = false; }
